### ISSUE TITLE
Safari CSS Bug

### ISSUE THREAD

**Issue by Toxantron** [Toxantron/scrumonline#10]
When using Safari the Cards on the MasterView are inverted. Use is not possible.

**Comment by Toxantron** [comment]
Reproduce:

[Session](http://scrumpoker.online/#/session/87) where cards should be hidden.
[Session](http://scrumpoker.online/#/session/88) where cards are inverted instead of flipped.

**Comment by Toxantron** [comment]
![img_0007](https://cloud.githubusercontent.com/assets/14931448/12884758/badecdc8-ce60-11e5-8d1b-61a61c59bc32.PNG)

**Comment by mkernel** [comment]
Have a look at the referenced commit - I worked on another branch.
I noticed a notice in the session controller (undefined index) which in turn broke the code (headers already sent) and fixed it.

**Comment by mkernel** [comment]
For your convenience i created a pull request.

**Comment by Toxantron** [comment]
Deployed and working!
