### ISSUE TITLE
Not showing 0.5 card

### ISSUE THREAD

**Issue by herbie68** [Toxantron/scrumonline#101]
I see in the code there is a deck added with a 0.5 card, but I miss that on the website.
I think all Fibonacci decks should include the 0.5 card.

For now we just use the coffee cup as 0.5 pointer

**Comment by Toxantron** [comment]
Hello, the `sample-config.php` in the repo and the `config.php` are not identical. Planning poker card sets are almost a religious topic - everyone has a slightly different favorite. I always planned to do an analysis on the database about the most common card decks and cards, then offer a valid pre-selection.

Additionally I think, I will introduce the option to select a custom deck upon session creation in a following version.

**Comment by herbie68** [comment]
That custom deck would be a perfect solution.

Best regards,

Herbert Nijkamp

Gerrit Peuscherstraat 43
7558 BA HENGELO

Mobiel: 06-23778057
Telefoon: 074-2773000

HTTP://herbertswerf.wordpress.com

Op vr 5 apr. 2019 20:05 schreef Thomas Fuchs <notifications@github.com>:
