### ISSUE TITLE
Class not Found: Doctrine\Common\Annotations\AnnotationRegistry

### ISSUE THREAD

**Issue by piapatricktresp** [Toxantron/scrumonline#102]
Hey, 
i followed exactly the documentations for nginx or apache and both systems and i encounter the same problem in both.

first of all, some sponsors.php is missing which i just created empty to move along.
But now after saving a session i get an error:
```
[error] 16655#16655: *39373 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in /var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php:152
Stack trace:
#0 /var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Configuration->newDefaultAnnotationDriver(Array, true)
#1 /var/www/scrumonline/src/bootstrap.php(11): Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(Array)
#2 /var/www/scrumonline/src/api.php(3): require_once('/var/www/...')
#3 {main}
  thrown in /var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php on line 152" while reading response header from upstream
```

Did i miss something ( the documentation is missing a couple things i guess ). ?

Thanks!

Patrick

**Comment by Toxantron** [comment]
Interesting, it seems to be the same as #98. I never had that, but I didn't reinstall for a while now. Maybe something with the packages. My version of doctrine might be outdated.

**Comment by piapatricktresp** [comment]
just a note further:
with  `locate *Ann*`

I have no search results for the missing file

/var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Annotation.php
/var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
/var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php
/var/www/scrumonline/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Export/Driver/AnnotationExporter.php
/var/www/scrumonline/vendor/doctrine/orm/tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php
/var/www/scrumonline/vendor/doctrine/orm/tests/Doctrine/Tests/ORM/Tools/Export/AnnotationClassMetadataExporterTest.php

Best,

Patrick

**Comment by Toxantron** [comment]
This reminds me of a weird bug we had at work caused by a *.lock file not being commited. Usually the versions in `composer.json` should not have breaking changes. Anyway I added my `composer.lock`. This should fix your issues for now.
I am currently updating(rewriting) the frontend to angular7. After that I will update the server to the latest versions and libraries. It might turn out as an ASP.NET Core rewrite.

**Comment by piapatricktresp** [comment]
I can confirm, that the composer.lock helped me to get it up and running.
Thank you!
