### ISSUE TITLE
Update Dockerfile to use php7 instead of php5 

### ISSUE THREAD

**Issue by GuestInCorle** [Toxantron/scrumonline#105]
I've tried to deploy the app using Docker and got this error 
```
user@host:~/scrumonline$ ./docker.sh prepare
Preparing repository for usage with docker
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
cp: cannot stat 'src/sample-config.php': No such file or directory
```
Before this I've invoked all the necessary commands from [Docker.md](https://github.com/Toxantron/scrumonline/blob/dev/doc/Docker.md).

I think that this problem appears because of dependency to php5 defined in [Dockerfile](https://github.com/Toxantron/scrumonline/blob/dev/docker/Dockerfile):

```
...
RUN apt-get update && \
    apt-get -y install supervisor \
    apache2 libapache2-mod-php5 \
    mysql-server mysql-client php5-mysql \
    php5-xdebug php5-curl php5-imagick \
curl wget vim
...
ADD php_config /etc/php5/apache2/php.ini
ADD php_config /etc/php5/cli/php.ini
...
ADD xdebug.ini /etc/php5/mods-available/xdebug.ini
...
```

Is Dockerfile need to be updated to use php7 instead of php5 to make Docker deployment successful?

**Comment by Toxantron** [comment]
I would have assumed that unless I update any of the packages the PHP version should be compatible. I think upgrading the whole project to PHP7.0 was discussed in another issue before.I generally don't mind, but for my remaining spare time I am currently focused on rebuilding the front-end.

If you provide an updated docker file I am happy to merge it. :-)

**Comment by Toxantron** [comment]
I merged the `composer.lock` into master. That should solve your problem as well until I find time to update the backend.

**Comment by TheGorf** [comment]
Sorry to reopen this. I was getting the similar error on docker.sh prepare:

`[ec2-user@ip-10-1-0-19 scrumonline]$ ./docker.sh prepare
Preparing repository for usage with docker
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 2
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
    - doctrine/common v2.7.3 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[v1.2.0].
    - Installation request for doctrine/common v2.7.3 -> satisfiable by doctrine/common[v2.7.3].`

I was looking at composer.lock. I just cloned the repo and edited composer.lock like so:

`[ec2-user@ip-10-1-0-19 scrumonline]$ diff composer.lock ../scrumonline_dev/composer.lock
373c373
< 		"php": "^5.6 || ^7.0"
---
>                 "php": "^7.0"`

This resolved my issue.

**Comment by Toxantron** [comment]
I have updated composer and am currently catching up on docker changes and try to build a new image with php7.3 in #107.
