### ISSUE TITLE
Unable to start via docker

### ISSUE THREAD

**Issue by k33ny** [Toxantron/scrumonline#106]
When trying to deploy with docker there seems to be some issues.

```bash
scrumonline$ ./docker.sh prepare
Preparing repository for usage with docker
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 2
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
    - doctrine/common v2.7.3 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[v1.2.0].
    - Installation request for doctrine/common v2.7.3 -> satisfiable by doctrine/common[v2.7.3].
```
Running `./docker.sh start` afterwards does work, however when i open up the site and create a session its ID is `undefined`

**Comment by ishanashams** [comment]
@k33ny I resolved that issue by deleting the composer.lock file, and you would also need to change doctrine/orm version to 2.6.* in composer.json file

However, even after all of the schemas were created, the session ids were still undefined.

**Comment by Toxantron** [comment]
It seems that old packages have been removed or their dependencies updated. Someone else [pointed out](https://github.com/Toxantron/scrumonline/issues/105#issuecomment-511603607) that deleting composer lock **and** updating PHP version works. In combination with docker that might require changing the docker file.

Hopefully I find time to fix the backend in the near future. Sorry. :-(

**Comment by Toxantron** [comment]
I have updated composer and am currently catching up on docker changes and try to build a new image with php7.3 in #107.

**Comment by JaphetManu** [comment]
+1

**Comment by JaphetManu** [comment]
I tried using your PR but im getting following error while running docker.sh prepare:

[ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

**Comment by gimmebytes** [comment]
@JaphetManu 

If you're using PHP7.3 you must update composer in the bin folder to get rid of this issue.

Just do the following:

> $ rm bin/composer
> $ wget https://getcomposer.org/composer-stable.phar
> $ mv composer-stable.phar bin/composer
> $ chmod a+x bin/composer

Then, everything should work - I just got this working on a ubuntu VM without docker and hat the same issue.

Cheers

**Comment by chrisns** [comment]
Hi,
Volume mounting the code base is a bit of an anti pattern, I wanted to stand this up in Kubernetes / google cloud run, but I'm lazy so I've not bothered actually refactoring to separate things out **yet**.
It's got current builds of the bases too
You can see the code here: https://github.com/chrisns/scrumonline
It's intended to be a superset on top of this repo
thoughts welcome

**Comment by Toxantron** [comment]
I like that very much. I never really got time to properly support docker and lately the project in general. I am even considering removing my docker files and linking to your repo! :-)

**Comment by ondrejchmelar** [comment]
Thank you! I had trouble with the old docker image last week. This is very useful now for remote work.

**Comment by chrisns** [comment]
@Toxantron I'll commit to tidying it up, updating all the deps and maintaining it if you do?

**Comment by Toxantron** [comment]
I'll try to find more time to the project, but will remove docker and link to your project in the [Deployment Docs](https://github.com/Toxantron/scrumonline/blob/dev/doc/Deployment.md) as soon as you tell me you're ready. :-) Then I can focus on rewriting the frontend as Angular7/8/9 and the backend to support more traffic. Was that your question?

**Comment by chrisns** [comment]
@Toxantron sounds great, justifies me spending a bit more time on it :)

**Comment by chrisns** [comment]
... will ping when ready

**Comment by Toxantron** [comment]
Removed docker support, maintained by @chrisns in the future.
