### ISSUE TITLE
Session Token containing period "." at end

### ISSUE THREAD

**Issue by glenelg96** [Toxantron/scrumonline#116]
When Generating session links sometimes the token contains a period "."

When sharing this link via slack or other services the hyperlink generated counts this as the end of a sentence and not as part of the link. 
Expected: <https://www.scrumpoker.online/join/206992?token=DCMnlFuRXLGwf5.GoR.cD.>
Result: <https://www.scrumpoker.online/join/206992?token=DCMnlFuRXLGwf5.GoR.cD>.

It would be nice if this could be fixed.

**Comment by Antnee** [comment]
This just bit us, too. Thanks Slack!
