### ISSUE TITLE
PHP Fatal error:  Uncaught RedisException: Connection refused 

### ISSUE THREAD

**Issue by DARL0K** [Toxantron/scrumonline#128]
I followed the installation guide, but on db creation step I have those errors.
I can't find any info about redis in the documentation.
nginx version: nginx/1.18.0
PHP 7.3
Ubuntu 18

`root@main:/var/www/html/scrum# ./vendor/bin/doctrine orm:generate-proxies
PHP Fatal error:  Uncaught RedisException: Connection refused in /var/www/html/s                                                                                                                                                             crum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php:137
Stack trace:
#0 /var/www/html/scrum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(137)                                                                                                                                                             : Redis->connect('127.0.0.1')
#1 /var/www/html/scrum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(70):                                                                                                                                                              Doctrine\ORM\Tools\Setup::createConfiguration(false, '/tmp', NULL)
#2 /var/www/html/scrum/src/bootstrap.php(11): Doctrine\ORM\Tools\Setup::createAn                                                                                                                                                             notationMetadataConfiguration(Array)
#3 /var/www/html/scrum/cli-config.php(3): require_once('/var/www/html/s...')
#4 /var/www/html/scrum/vendor/doctrine/orm/bin/doctrine.php(48): require('/var/w                                                                                                                                                             ww/html/s...')
#5 /var/www/html/scrum/vendor/doctrine/orm/bin/doctrine(4): include('/var/www/ht                                                                                                                                                             ml/s...')
#6 {main}
  thrown in /var/www/html/scrum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup                                                                                                                                                             .php on line 137
root@main:/var/www/html/scrum# ./vendor/bin/doctrine orm:generate-proxies
PHP Fatal error:  Uncaught RedisException: Connection refused in /var/www/html/s                                                                                                                                                             crum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php:137
Stack trace:
#0 /var/www/html/scrum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(137)                                                                                                                                                             : Redis->connect('127.0.0.1')
#1 /var/www/html/scrum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(70):                                                                                                                                                              Doctrine\ORM\Tools\Setup::createConfiguration(false, '/tmp', NULL)
#2 /var/www/html/scrum/src/bootstrap.php(11): Doctrine\ORM\Tools\Setup::createAn                                                                                                                                                             notationMetadataConfiguration(Array)
#3 /var/www/html/scrum/cli-config.php(3): require_once('/var/www/html/s...')
#4 /var/www/html/scrum/vendor/doctrine/orm/bin/doctrine.php(48): require('/var/w                                                                                                                                                             ww/html/s...')
#5 /var/www/html/scrum/vendor/doctrine/orm/bin/doctrine(4): include('/var/www/ht                                                                                                                                                             ml/s...')
#6 {main}
  thrown in /var/www/html/scrum/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup                                                                                                                                                             .php on line 137
`

**Comment by Toxantron** [comment]
With connection refused I assume it's your database settings, that are incorrect. Check your `config.php`.

**Comment by Toxantron** [comment]
Any updates?

**Comment by DARL0K** [comment]
Sorry for the long answer. The DB settings are right.
