### ISSUE TITLE
Card values

### ISSUE THREAD

**Issue by Toxantron** [Toxantron/scrumonline#14]
The values '0', '?' and a coffee cup should be available as well.

Short term solution: 
Include those values but without modification to the evaluation algorithm.

Later the evalution process should somehow highlight the '?' or coffee cup to indicate the teams need for a break or further explanation.

Long term solution:
Every team is different. The Master View should feature a settings panel where the Card-Stack can be chosen as well as other options.

**Comment by marcelloh** [comment]
What is the evaluation algorithm?
And what if  the 0 and 1/2 card have just that as value)
and the ? has 1000 as value, and the coffeecup is a negative value?
Would your evaluation still work?
(didn't look at the software, but it looks like a good idea)

**Comment by Toxantron** [comment]
That is literally a brilliant idea. ;-)

And it wouldn't be to much effort. We would only need to split card-value and displayed character and that only on the server side. The biggest part is probably displaying different value sets in the Master View. For a first start we could use the [config](https://github.com/Toxantron/scrumonline/blob/master/src/sample-config.php#L15) to test it.

Unless you want to give it a try, I'll look into it on the weekend. I will create a branch for it, so if you want to contribute simply create a PR against it.

**Comment by marcelloh** [comment]
I think I leave it up to you. 4 now ;-)
BTW. I tried it on my mobile also, but I needed to scroll. Perhaps make it a more responsive design?

**Comment by Toxantron** [comment]
> but I needed to scroll. Perhaps make it a more responsive design?

Which view? The Master View only scales nicely till tablet size. The member view is optimized for mobile devices. Home and sessions should be very responsive on all screens. I didn't put more effort into it since most teams will use master view on bigger screen and join via smartphone.

Can you confirm this assumption?

**Comment by marcelloh** [comment]
the member view was too big on my mobile (using Chrome on Android, on an Asus Zenfone 3)
The assumption master view on bigger screen seems legit to me.

**Comment by Toxantron** [comment]
@marcelloh now I see. Yes the member view requires minimal vertical scrolling. Which in my oppinion is fine for responsive design. Never the less I could try to adjust size in the way that all cards fit the screen and only instructions at the bottom require scrolling.

I'll do the different cards first and by then the new number of cards will require different element sizes anyway.

**Comment by marcelloh** [comment]
My thoughts also :-)
You can always style the cards based on screen width, like this:
```
@media only screen and (max-width: 300px)
{
    .Card {
        font-size: 14px !important;
    }
}
@media only screen and (max-width: 600px)
{
    .Card {
        font-size: 16px !important;
    }
}
```

**Comment by Toxantron** [comment]
[I know](https://github.com/Toxantron/scrumonline/blob/master/src/css/scrumonline.css#L73). ;-)

But if users can select which values they want there is flexible number of cards on the screen and for this makes a one-size fits all more complicated. I will probably just assign @dbeuchler to figure this out.

**Comment by Toxantron** [comment]
I am half way in. Card sets can be configured and and selected on the creation view. Should be done tomorrow. :-)

Thanks again for the hint.
