### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by Toxantron** [Toxantron/scrumonline#34]
After Redmine was deleted we should add a plugin for Gitlab integration instead.

**Comment by amenk** [comment]
Why was redmine deleted?

**Comment by Toxantron** [comment]
We had problems with CORS and Google analytics showed no usage, so we didn't think it was worth the effort. But if you need it, we can probably use the solution we have for JIRA to work around CORS.

**Comment by egel** [comment]
I would like to also have a small additional feature to use custom gitlab instance (define custom URL to not only use the gitlab.com) 🙂

**Comment by Toxantron** [comment]
@dbeuchler already started working on this, but doesn't have the time to continue. I will try to pick up, where he left off.

**Comment by egel** [comment]
Hey @dbeuchler, how goes the progress with the feature? 🙂

**Comment by Toxantron** [comment]
To be honest I haven't started yet. We talked about it and @dbeuchler will push his version. Do you have experience and time to participate?

**Comment by Toxantron** [comment]
I finally found some time to get this started. You can track the progress in #96.

I use https://gitlab.beuchler.eu/tfuchs/scrum-debug to debug the plugin.

**Comment by Toxantron** [comment]
Solved in 1af915f10c18a0b1a466eb0fdc517930083753d6
