### ISSUE TITLE
Show session id on session view and add join button

### ISSUE THREAD

**Issue by dbeuchler** [Toxantron/scrumonline#39]
If you want to join a session by the session view, it would be nice if the id is visible
Additionally a "join" button will be nice.

**Comment by Toxantron** [comment]
The idea was to not show session ids publicly. I should not be able to join another session even if technically you could create one and calculate back the sequential id.

But I could add a join button that requires passwort for private sessions.

**Comment by dbeuchler** [comment]
Sorry, it was a train of thought and solution in one 👅 
An additional join button will be nice :-)

**Comment by Toxantron** [comment]
I created [a branch](https://github.com/Toxantron/scrumonline/tree/issue-39) to refactor the sessions view and resolve the issue.

**Comment by Toxantron** [comment]
Feature was added, I am sure your delicate eye will want to restyle it @dbeuchler. :nerd_face:
