### ISSUE TITLE
How to install scrumonline on the webserver

### ISSUE THREAD

**Issue by kdeenkhoorn** [Toxantron/scrumonline#40]
I ave tried to install scrumonline on my webserver but it does not seem to work.
Database tables are created but if i try to start a new session nothing happens.

What should be the root of the website, the src directory ?

Thanks in advance,

Klaas Eenkhoorn

**Comment by Toxantron** [comment]
> What should be the root of the website, the src directory ?

Yes, the webroot is the `src` directory. This information got lost when @dbeuchler updated the docs. I will fix it later. 

Which webserver are you using? If you use Apache could you post your error log? I assume your apache has no mod_rewrite enabled. I will update this in the docs as well.

**Comment by dbeuchler** [comment]
The apache docs Should be updated by someone who still uses it. 

Use chrome and check the api requests. The exceptions will be written in the response json. Better will be an error 500 or similar.

**Comment by Toxantron** [comment]
@dbeuchler I will update them. I think the info is missing for nginx as well. ;-)

**Comment by kdeenkhoorn** [comment]
The access logging is telling me when i push the button 'Create' 
192.168.2.11 - - [05/Apr/2017:20:58:41 +0200] "POST /api/session/create HTTP/1.1" 404 529 "http://ontwikkel.phantasyworld.intern/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

There is no error captured in the error log.

**Comment by kdeenkhoorn** [comment]
if i push the join button i get:
192.168.2.11 - - [05/Apr/2017:21:17:05 +0200] "POST /api/session/join HTTP/1.1" 404 527 "http://ontwikkel.phantasyworld.intern/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

**Comment by Toxantron** [comment]
This seems to be a mod_rewrite error. Follow the apache docs on how to enable it and also enable .htaccess in Apache.

I will update the docs this weekend, I am currently not at a computer.

**Comment by kdeenkhoorn** [comment]
I have in general mod_rewrite enabled on the server but not for this virtualhost. Unfortunately i could not find anything in the installation manual about rewrite rules but i will wait for them to appear on the site.

Is there a chance that this application will work on php 5.3.3 ?

**Comment by kdeenkhoorn** [comment]
Allright now it works, i had to enable the usage of .htaccess which includes the mod_rewrite rules.
I did not take notice of this file until you've mentioned the existance of it.

Thanks!

By the way is it expected behaviour that the browser keeps polling the webserver and thus spamming the access log ?

**Comment by kdeenkhoorn** [comment]
The supposed update of the documentation would have helped me a lot initially. It gives the missing link on how to install the application on the webserver. Thanks for the quick response!
I have also noticed the start of the development of a JIRA plugin, way to go guys !
Will be back more often to follow the growth of this diamond ... ;-)

**Comment by Toxantron** [comment]
Perfect @kdeenkhoorn, as soon as @dbeuchler reviews the changes to nginx I will merge it and close the issue.

**Comment by dbeuchler** [comment]
Merged the updated documentation in 53cbd5f63128452cf9cb02e5561d603c0dab96a
