### ISSUE TITLE
Jira integration

### ISSUE THREAD

**Issue by filipgolonka** [Toxantron/scrumonline#41]
Would be nice to import Jira issues automatically during planning ;)

**Comment by Toxantron** [comment]
I agree.

It was one of the ticketing systems I orginally thought of. Including Github was easy and @dbeuchler already started importing from Gitlab. However I do not have Jira or a Jira project to test it on.

If you are willing to contribute and have a system for testing, there is [a section in the developer docs](https://github.com/Toxantron/scrumonline/blob/master/doc/Developer-Documentation.md#ticketing-plugin) how to add a ticketing system.

**Comment by filipgolonka** [comment]
I will try to help here :)

**Comment by Toxantron** [comment]
@filipgolonka great. How about making this a joint effort? I will create a branch for Jira and try to prepare the plugin and you can join in and test against your system. As soon as it is stable I will merge to _master_ and deploy to the cloud version.

**Comment by filipgolonka** [comment]
@Toxantron sure, feel free to start after weekend, because I won't be able to do this earlier :)

**Comment by Toxantron** [comment]
Since I won't have too much time for this during the week, I will try to get a head start tomorrow morning.

**Comment by Toxantron** [comment]
Closed by 048a1c7.

**Comment by filipgolonka** [comment]
@Toxantron checked Jira integration and it is not working. 
`POST https://www.scrumpoker.online/api/jira/getIssues 500 (Internal Server Error)`
when I try to load issues. Can you check logs and send me the info, so I will fix it?

**Comment by Toxantron** [comment]
Not necessary, it seems to be my fault:

````log
01.06.2017 08:40:54 scrumpoker.online [client 5.226.119.0] PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\\Client' not found in /mnt/web001/e1/12/56920712/htdocs/src/controllers/jira-controller.php:22, referer: https://www.scrumpoker.online/
````

I forgot to copy composer dependencies onto prod machine. Will fix it later today.

**Comment by Toxantron** [comment]
@filipgolonka could you check again? I don't have a target project to test against.

**Comment by filipgolonka** [comment]
Done, works now
