### ISSUE TITLE
HTTP 503 - Service unavailable

### ISSUE THREAD

**Issue by Toxantron** [Toxantron/scrumonline#47]
The increased popularity of www.scrumpoker.online has created scaling issues. The constant polling of master and member view exceeds the servers capacity.

Before renting more powerful hardware the polling time should be changed to a self-adjusting, dynamic algorithm. Everytime a request fails it will increase the polling time, if it goes through it is decreased. By increasing faster than decreasing a success rate of less then 80% will still keep increasing the factor till it stabilizes. 

Somehting like:

````js
scrum.pollingScale = (function() {
  var current = 2.0;

  this.scale = function(value) {
    return value * current;
  };
  
  this.success = function() {
    if (current > 1.0)
      current -= 0.05;
  };

  this.failed = function() {
    if (current < 5.0)
      current += 0.2;
  };
})();
````

**Comment by mkernel** [comment]
How about switching server side technology to something less request based? Websockets could help  a lot - though not with a request-based php framework on the server side.

**Comment by Toxantron** [comment]
True, but just speaking from personal experience enterprise networks and firewalls tend to block websockets. Especially since the [leading enterprise firewall and proxy](https://kc.mcafee.com/corporate/index?page=content&id=KB84052&actp=null&showDraft=false&platinum_status=false&locale=en_US&viewlocale=en_US) does not properly support it.

But in the long run this is the better solution for sure. Till then dynamic polling adoption hopefully keeps the site running a little longer.

**Comment by mkernel** [comment]
So you're thinking about the chicken-n-egg problem here? No firewall will change without someone demanding it :) and frameworks like https://socket.io fall back to polling automatically.

The problem I see with dynamic polling: it will degrade to a level where users will notice the delays. 

Anyway, switching to websockets won't help without a server-side overhaul... so the dynamic polling resolution is the best thing to do in the short term.

You might also squeeze a lot more requests out of your web workers by optimizing the code running the ajax endpoints.

**Comment by Toxantron** [comment]
Yeah, I noticed there is a lot of potential in the query speed. I totally agree.

Roadmap: 
1. Dynamic polling
2. Optimize server
3. (Partial) server rewrite in ASP.Net

**Comment by mkernel** [comment]
Great :)

**Comment by dbeuchler** [comment]
I like the rewrite plans in ASP.Net 👍

**Comment by Toxantron** [comment]
I don't like how this affects my schedule, so we are talking 2018 probably.
