### ISSUE TITLE
Check/implement rights

### ISSUE THREAD

**Issue by jfversluis** [Toxantron/scrumonline#56]
It seems that every participant of a session is able to remove other members from the session, even in spectator mode. I didn't try any other scenarios, but it seems some sanity check is in order in regard to the rights.

**Comment by Toxantron** [comment]
Yeah, that is definetly an issue. The only way to prevent this right now are private sessions. I do not want to add a user management, but for this issue it might be enough to add cookies wether you are owner of the session or not.

**Comment by jfversluis** [comment]
Yeah, my thoughts exactly. Just set the initiator as the owner and only give him rights to do anything that smells like managing the session.

**Comment by Toxantron** [comment]
It's been almost a year now, but I will finally approach this topic in #80.
