### ISSUE TITLE
Create an endpoint to retrieve card sets

### ISSUE THREAD

**Issue by jfversluis** [Toxantron/scrumonline#58]
It would be nice to have an endpoint which provides me with the available card sets.
The way it is now, I would have to hardcode them into the client, when we decide to add a new set, this would now require the client(s) to update as well. I think this should be prevented.

**Comment by Toxantron** [comment]
There is an endpoint to receive the cardset of the session. This should be sufficient if the app is only used for the member mode. If you want to include the MasterView as well, I will add an endpoint.

**Comment by jfversluis** [comment]
That is indeed the cardset for that session, but I'd like to have one for all sets that are available.
So, when you create a session I can generate a dropdown (or equivalent) with all the cardsets that are available at that time dynamically instead of having to hardcode them.

**Comment by Toxantron** [comment]
While I will add the endpoint one might still argue for the use case of creating a session on a mobile device. :-)
