### ISSUE TITLE
Idea: Add a timer/stopwatch for time-boxed discussions

### ISSUE THREAD

**Issue by dbeuchler** [Toxantron/scrumonline#66]
The master view should have an integrated timer or stopwatch to have the discussion time in mind.

**Comment by Toxantron** [comment]
There already is [a statistic](https://github.com/Toxantron/scrumonline/blob/master/src/controllers/statistics/DiscussionTime.php) for that. Isn't that enough?

**Comment by dbeuchler** [comment]
My idea was to see the time of the current poll live as a stopwatch to stop discussion after a negotiated time.

**Comment by dbeuchler** [comment]
Or maybe a stopwatch seperated from the poll with start, stop and reset buttons

**Comment by Toxantron** [comment]
Ah ok, shouldn't be too much effort. I am currently implementing #64 and will do #65 next.
