### ISSUE TITLE
status=backlog doesn't work on Jira

### ISSUE THREAD

**Issue by PureTryOut** [Toxantron/scrumonline#74]
If adding a Jira connection, no issues appear if `status=backlog` is used in JQL. If removed, *all* issues appear (obviously) fine. Yes, I've made sure there are in fact stories and tasks in the backlog.

**Comment by Toxantron** [comment]
The JIRA plugin was contributed, so maybe @filipgolonka can answer this. Have you verified the JQL works if you use another REST-client to query the API?

**Comment by filipgolonka** [comment]
@Toxantron didn't touch it during long long time, but I will check it today/tomorrow and will keep you posted here. 

@PureTryOut can you check in your Jira instance, if querying by JQL `status=backlog` works and returns correct results? I'm wondering if specific Jira config might affect the import (i.e. introducing custom field called "Status" or something similar)

**Comment by PureTryOut** [comment]
Sorry, I do not have administrator access to this Jira instance, it's hosted outside of my control.

Querying the url manually gave back an empty result, so I guess this problem is outside of scrumonline. Sorry for bothering you guys with it!

**Comment by Toxantron** [comment]
Never mind, I hope you find a solution. ;-)
