### ISSUE TITLE
JIRA Integration 500 errors

### ISSUE THREAD

**Issue by bcrigler** [Toxantron/scrumonline#75]
Hey I love the tool it's great.  I just would love to use the JIRA integration.  We have JIRA cloud with a custom atlassian subdomain.  Not sure if I need to do any setup on my end in JIRA cloud but this is the response I'm getting from the API request.

`angular.js:12587 POST https://scrumpoker.online/api/jira/getIssues 500 ()`
`(anonymous) @ angular.js:12587`
`p @ angular.js:12332`
`(anonymous) @ angular.js:12084`
`(anonymous) @ angular.js:16832`
`$digest @ angular.js:17971`
`$apply @ angular.js:18269`
`(anonymous) @ angular.js:26999`
`dispatch @ jquery.min.js:3`
`r.handle @ jquery.min.js:3`
`angular.js:14525 Possibly unhandled rejection: {"data":"","status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/jira/getIssues","data":"base_url=https%3A%2F%2Frezora.atlassian.net&username=brian%40rezora.com&password=#########&project=rezora+Software+Development&jql=issuetype%3Dstory+and+status%3Dbacklog","headers":{"Content-Type":"application/x-www-form-urlencoded","Accept":"application/json, text/plain, */*"}},"statusText":""}`

**Comment by Toxantron** [comment]
Hey and thanks for the feedback. We had a similar ticket #74 a while ago that had issues with the same filter `status=backlog`. I don't have access to JIRA myself, but maybe you can verify your server supports REST calls by trying with a standard REST client yourself. I will have a look at the server logs if I find anything.

**Comment by Toxantron** [comment]
So, any new insights?

**Comment by Toxantron** [comment]
Closed for now.
