### ISSUE TITLE
It is possible to join private sessions without invitation

### ISSUE THREAD

**Issue by paulikt** [Toxantron/scrumonline#76]
As sessionId-s are assigned sequentially one is capable of forging a valid join url to a private session simply by observing the sessionId of a non-private session above/below of the private session in the session list, and then decreasing/increasing the observed sessionId in the join link.

A straightforward solution would be to include some randomness in the sessionId generation or to ask for the password when joining. (It could be included in the link as a GET parameter if the service is over SSL/TLS)

**Comment by paulikt** [comment]
Furthermore all active sessionID's are conveniently listed here:
https://scrumpoker.online/api/session/active

**Comment by Toxantron** [comment]
Yes, I am aware of this. Even worse you can not just join it, but over the API delete members etc. - every call described in [the API doc](https://github.com/Toxantron/scrumonline/blob/master/doc/swagger.yaml) is performed without any authentification.

In #56 I picked this up, but to be honest have not found the spare time to properly do this. Unfortunately it's no small change but requires a little more effort. For now I just hope that users respect each other, but eventually this needs to be fixed.

**Comment by Toxantron** [comment]
If you take a look at the JavaScript you will see that the password restriction to join a private session over the UI is completely implemented in the client and an array of allowed session ids.

For real security this requires session tokens generated by the server and passed to the client as cookies once the password was entered correctly. The token is then validated with every API call. To not break UX the QR-Code and join-URL could contain the token. It would be impossible to forge and still not require the password to join.

**Comment by Toxantron** [comment]
You will be glad to hear that I finally have some time to look at this. Feel free to track the progress in MR #80.
