### ISSUE TITLE
Select card is broken and can't create session

### ISSUE THREAD

**Issue by Deses** [Toxantron/scrumonline#79]
Hi! I was about to create a session but couldn't because the Card select is not available...
I'm using the latest Chrome version on Windows 10.

![image](https://user-images.githubusercontent.com/1654959/39046138-6f264a2a-4495-11e8-8fe7-652e3d2922da.png)

**Comment by Deses** [comment]
The issue only happened with Adblock enabled, maybe take a look at that...

**Comment by Toxantron** [comment]
AdBlock detects the usage of Google Analytics and blocks the pages JavaScript. However I remember seeing a PR somewhere that whitelisted the URL. Have you tried updating AdBlock?
