### ISSUE TITLE
DB Scheme without docker

### ISSUE THREAD

**Issue by Demian87** [Toxantron/scrumonline#81]
Hi! How may I get SQL scheme without using docker?
Are there any sql scripts to create scheme?

**Comment by Demian87** [comment]
Yes, I need help.
I'm using virtual hosting, so I don't have any access to command line there. Only myphpadmin for administer databases.

**Comment by Toxantron** [comment]
I have been through that. I found the easiest way is to create the database locally using the CLI, dump it and restore the dump in PHP MyAdmin. I did the same to deploy to [scrumpoker.online](https://scrumpoker.online).

**Comment by Demian87** [comment]
I spent two hours, trying to make docker image work =(( I didn't succeed.

If you are able to dump db scheme, I'll appreciate your help.

**Comment by Toxantron** [comment]
I am sorry to hear that, but you don't need docker. You can just clone the repo and execute the commands. But I'll get you a dump or script when I get home.

**Comment by Toxantron** [comment]
Here is your script - but you will still need a CLI to generate the doctrine proxies.

```sql
CREATE TABLE members (id INT AUTO_INCREMENT NOT NULL, session_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_45A0D2FF613FECDF (session_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE polls (id INT AUTO_INCREMENT NOT NULL, session_id INT DEFAULT NULL, topic VARCHAR(255) NOT NULL, startTime DATETIME NOT NULL, endTime DATETIME NOT NULL, result DOUBLE PRECISION NOT NULL, consensus TINYINT(1) NOT NULL, INDEX IDX_1D3CC6EE613FECDF (session_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE sessions (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, isPrivate TINYINT(1) NOT NULL, password VARCHAR(255) DEFAULT NULL, token VARCHAR(255) NOT NULL, cardSet INT NOT NULL, lastAction DATETIME NOT NULL, currentPoll_id INT DEFAULT NULL, INDEX IDX_9A609D13DD3787E (currentPoll_id), INDEX date_idx (lastAction), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE votes (id INT AUTO_INCREMENT NOT NULL, poll_id INT DEFAULT NULL, member_id INT DEFAULT NULL, value DOUBLE PRECISION NOT NULL, highlighted TINYINT(1) NOT NULL, INDEX IDX_518B7ACF3C947C0F (poll_id), INDEX IDX_518B7ACF7597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE members ADD CONSTRAINT FK_45A0D2FF613FECDF FOREIGN KEY (session_id) REFERENCES sessions (id);
ALTER TABLE polls ADD CONSTRAINT FK_1D3CC6EE613FECDF FOREIGN KEY (session_id) REFERENCES sessions (id);
ALTER TABLE sessions ADD CONSTRAINT FK_9A609D13DD3787E FOREIGN KEY (currentPoll_id) REFERENCES polls (id);
ALTER TABLE votes ADD CONSTRAINT FK_518B7ACF3C947C0F FOREIGN KEY (poll_id) REFERENCES polls (id);
ALTER TABLE votes ADD CONSTRAINT FK_518B7ACF7597D3FE FOREIGN KEY (member_id) REFERENCES members (id);
```

**Comment by Toxantron** [comment]
I updated [the documentation](https://github.com/Toxantron/scrumonline/blob/master/doc/Deployment-Database.md) to cover your use-case as well.

**Comment by Demian87** [comment]
I created the DB from your code, but I still recieve 500 Error, when I try to start a new session. I think the problem in DB connection. I was not able to execute those three commands from your instruction =( How did you manage to launch your project on virtual hosting?

**Comment by Toxantron** [comment]
I did the following:

1. Clone the repo
2. Create config with values from the provider `cp src/sample-config.php src/config.php` 
2. Run deployment commands to install composer dependencies and generate proxies
3. Copy entire working copy **without** `.git` folder to the hoster via FTP
4. Create database
5. Configure web-root path to `src/`
6. Should work.

**Comment by Demian87** [comment]
Thank you for instructions. I'm able to do everything except generating proxies. the script resurns errors.

**Comment by Toxantron** [comment]
Can you post the output from the script?

**Comment by Demian87** [comment]
I get these messages

` [Doctrine\DBAL\Exception\DriverException]
  An exception occurred in driver: could not find driver

  [Doctrine\DBAL\Driver\PDOException]
  could not find driver

  [PDOException]
  could not find driver`

**Comment by Toxantron** [comment]
Good to know.

I assume `$ ./vendor/bin/doctrine orm:schema-tool:create --dump-sql >> schema.sql` should work without mysql no that you found a fix for doctrine.

**Comment by Demian87** [comment]
Upgraded php version to 7.2 and it's working now. Thanks!
