### ISSUE TITLE
docker.sh stop other containers & move prepare inside container

### ISSUE THREAD

**Issue by klepek** [Toxantron/scrumonline#90]
1] docker.sh stops other containers
Current code in start:
docker ps -a -q -> this returns all running containers
docker stop $running -> this passes all running containers and stops them

Add grep to docker ps to select only correct containers. 

2] prepare should be in container
In most cases, docker server and/or kubernetes cluster will not have php locally installed. Prepare of container should be done inside of container and not outside.

I have moved this login inside bash script, and modified docker.sh to run this script from within a container. See pull request: 

Pull request here: https://github.com/Toxantron/scrumonline/pull/89

**Comment by Toxantron** [comment]
Since #89 was merged, I think this is done?
